### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by colemartens** [vinmorel/MapleWrapper#1]
ERROR: Could not find a version that satisfies the requirement pywin32==225 (from versions: 302, 303)
ERROR: No matching distribution found for pywin32==225

getting this error, on windows with up to date python.

**Comment by vinmorel** [comment]
What python version are you using? 

EDIT: 

Seems like python 3.10.x isn't compatible with pywin32==225. For now you can use python 3.8.x, I'll try to fix this compatibility issue

**Comment by colemartens** [comment]
3.10, appreciate the response.
